# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
- group: azure-repos-sync

jobs:
- job: Build
  displayName: "Build, Test and Publish"

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'echo "ref: $(Build.SourceBranch)" > $(Build.SourcesDirectory)/.git/ADO_OVERRIDE_HEAD'
    displayName: 'Set Source Branch'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
    displayName: 'Build the Module'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      testRunTitle: 'Run unit tests'
    displayName: 'Run Unit Tests'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
    displayName: 'Package for NuGet'

  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with NuGet Feed'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '5f8d36de-7004-4c36-a8b5-8a4bda9eb598/c2949ad7-bda3-4f23-a41b-3109c9419cb7'
      allowPackageConflicts: true
    displayName: 'Push to NuGet Feed'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

- job: Sync
  displayName: "Sync with Azure Repos"

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        git remote add target https://tlylz:$(SYNC_PAT)@dev.azure.com/tlylz/namomo/_git/plagiarism
        git checkout $(Build.SourceBranchName)
        git pull target $(Build.SourceBranchName) --tags
        git push target --all
        git push target HEAD:$(Build.SourceBranchName) --tags
    displayName: 'Sync via Git Tools'
