version: '3.1'

services:
    pds:
        build:
            context: .
            dockerfile: Dockerfile
        image: namofun/pds:latest
        container_name: pds_app
        restart: on-failure
        links:
            - mariadb
        environment:
            ConnectionStrings__UserDbConnection: 'Server=mariadb;Port=3306;Database=pds;User=pds;Password=!!your_password!!;Character Set=utf8;TreatTinyAsBoolean=true;'
            ConnectionStrings__UserDbConnectionType: 'MySql'
            TZ: 'Asia/Shanghai'
        ports:
            - 49846:80

    mariadb:
        image: mariadb
        container_name: pds_mariadb
        environment:
            MYSQL_DATABASE: 'pds'
            MYSQL_USER: 'pds'
            MYSQL_PASSWORD: '!!your_password!!'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - /data/pds/database:/var/lib/mysql
