namespace Xylab.PlagiarismDetect.Frontend.Python
{
    public enum TokenConstants : int
    {
        FILE_END = 0,
        SEPARATOR_TOKEN = 1,
        IMPORT = 2,
        CLASS_BEGIN = 3,
        CLASS_END = 4,
        METHOD_BEGIN = 5,
        METHOD_END = 6,
        ASSIGN = 7,
        WHILE_BEGIN = 8,
        WHILE_END = 9,
        FOR_BEGIN = 10,
        FOR_END = 11,
        TRY_BEGIN = 12,
        EXCEPT_BEGIN = 13,
        EXCEPT_END = 14,
        FINALLY = 15,
        IF_BEGIN = 16,
        IF_END = 18,
        APPLY = 19,
        BREAK = 20,
        CONTINUE = 21,
        RETURN = 22,
        RAISE = 23,
        DEC_BEGIN = 24,
        DEC_END = 25,
        LAMBDA = 26,
        ARRAY = 27,
        ASSERT = 28,
        YIELD = 29,
        DEL = 30,
        WITH_BEGIN = 31,
        WITH_END = 32,
        NUM_DIFF_TOKENS = 33,
    }
}
